### ISSUE TITLE
Trigger : covoit->trajet_type 

### ISSUE THREAD

**Issue by rotchotcho** [rotchotcho/CarShare#18]
Si un covoiturage possédant les mêmes ville de départ et d'arrivée est proposé par un autre conducteur, le trigger ne donc pas réaliser l'insertion dans trajet type car il est déjà connu. L'erreur générée "duplicate entry sur primay key" est malheureusement bloquante. 

---> On ne peut pas insérer cette nouvelle proposition de covoiturage à cause de ce trigger dans cet état.

**Comment by rotchotcho** [comment]
Si un covoiturage possédant les mêmes ville de départ et d'arrivée est proposé par un autre conducteur, le trigger ne donc pas réaliser l'insertion dans trajet type car il est déjà connu. L'erreur générée "duplicate entry sur primay key" est malheureusement bloquante.

---> On ne peut pas insérer cette nouvelle proposition de covoiturage à cause de ce trigger dans cet état.

**Comment by Clemlifashou** [comment]
Ca marche
